// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOSh6ye8myY0c5cvFS0hMNMvPsH_g9fEs',
    appId: '1:569120086582:web:49925c214c1949414f1697',
    messagingSenderId: '569120086582',
    projectId: 'leitner-71bd9',
    authDomain: 'leitner-71bd9.firebaseapp.com',
    storageBucket: 'leitner-71bd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAAaE1vm7cGXUOIBYayLxoBv-Q6J8Vsg',
    appId: '1:569120086582:android:a9a110be4e2708204f1697',
    messagingSenderId: '569120086582',
    projectId: 'leitner-71bd9',
    storageBucket: 'leitner-71bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUEYxjopvjPFc9Ht3YPCKQkNu-WlZlh4',
    appId: '1:569120086582:ios:72acc0709117af204f1697',
    messagingSenderId: '569120086582',
    projectId: 'leitner-71bd9',
    storageBucket: 'leitner-71bd9.appspot.com',
    iosBundleId: 'com.doktity.leitner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtUEYxjopvjPFc9Ht3YPCKQkNu-WlZlh4',
    appId: '1:569120086582:ios:0ff6f99eac74363d4f1697',
    messagingSenderId: '569120086582',
    projectId: 'leitner-71bd9',
    storageBucket: 'leitner-71bd9.appspot.com',
    iosBundleId: 'com.doktity.leitner.RunnerTests',
  );
}
